name: cmake-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: update dependencies
      run: sudo apt-get install software-properties-common && sudo apt update && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install -y g++-13 gcc-13 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 13 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 13
    - name: configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
